"""add book_episodes table

Revision ID: d92c220e0637
Revises: f8028b2e5271
Create Date: 2026-04-21 18:11:21.773213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd92c220e0637'
down_revision: Union[str, Sequence[str], None] = 'f8028b2e5271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_episodes',
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('hook', sa.String(), nullable=False),
    sa.Column('original_text', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('cliffhanger', sa.String(), nullable=False),
    sa.Column('character', sa.String(), nullable=False),
    sa.Column('character_role', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_episodes_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'number', name=op.f('pk_book_episodes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_episodes')
    # ### end Alembic commands ###
