"""add books and book_notes tables

Revision ID: f8028b2e5271
Revises: 2fdcc2a232a8
Create Date: 2026-04-20 23:41:55.794566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8028b2e5271'
down_revision: Union[str, Sequence[str], None] = '2fdcc2a232a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['book_categories.id'], name=op.f('fk_books_category_id_book_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books')),
    sa.UniqueConstraint('title', name=op.f('uq_books_title'))
    )
    op.create_table('book_notes',
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_notes_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'id', name=op.f('pk_book_notes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_notes')
    op.drop_table('books')
    # ### end Alembic commands ###
